-- MySQL Script generated by MySQL Workbench
-- Tue Mar 20 17:41:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fleamarket
-- -----------------------------------------------------
-- 高校二手市场
DROP SCHEMA IF EXISTS `fleamarket` ;

-- -----------------------------------------------------
-- Schema fleamarket
--
-- 高校二手市场
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fleamarket` DEFAULT CHARACTER SET utf8 ;
USE `fleamarket` ;

-- -----------------------------------------------------
-- Table `fleamarket`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`admin` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `tel` VARCHAR(11) NULL,
  `email` VARCHAR(50) NULL,
  `last_login` TIMESTAMP NOT NULL,
  `flag` INT NOT NULL COMMENT '0：超级管理员、1：普通管理员',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`user` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `nickname` VARCHAR(16) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `photo` VARCHAR(50) NOT NULL,
  `sex` CHAR(2) NOT NULL,
  `birthday` DATE NULL,
  `city` VARCHAR(30) NULL,
  `school` VARCHAR(50) NULL,
  `signature` VARCHAR(100) NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '0：锁定、1：正常',
  `star_count` INT NOT NULL DEFAULT 0,
  `like_count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`role` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`permission` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`admin_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`admin_role` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`admin_role` (
  `admin_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `fk_admin_role_admin_idx` (`admin_id` ASC),
  INDEX `fk_admin_role_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_admin_role_admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `fleamarket`.`admin` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_admin_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fleamarket`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`role_permission` (
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  INDEX `fk_role_permission_role1_idx` (`role_id` ASC),
  INDEX `fk_role_permission_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fleamarket`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `fleamarket`.`permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`announcement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`announcement` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`announcement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`category` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `pid` INT NULL COMMENT '父分类id',
  PRIMARY KEY (`id`),
  INDEX `fk_category_category1_idx` (`pid` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`pid`)
    REFERENCES `fleamarket`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品分类';


-- -----------------------------------------------------
-- Table `fleamarket`.`treasure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`treasure` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`treasure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(50) NOT NULL COMMENT '主图',
  `category` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `fare` DOUBLE NOT NULL,
  `total` DOUBLE GENERATED ALWAYS AS (price+fare),
  `sell_type` INT NOT NULL DEFAULT 1 COMMENT '【售卖类型】1：正常、2：秒杀',
  `status` INT NOT NULL DEFAULT 1 COMMENT '【出售状态】0：下架、1：在售、2：已售出',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数',
  `comment_count` INT NOT NULL DEFAULT 0 COMMENT '评论数',
  `new_degree` INT NOT NULL COMMENT '新旧程度',
  `page_view` INT NOT NULL DEFAULT 0 COMMENT '浏览量',
  PRIMARY KEY (`id`),
  INDEX `fk_treasure_category1_idx` (`category` ASC),
  CONSTRAINT `fk_treasure_category1`
    FOREIGN KEY (`category`)
    REFERENCES `fleamarket`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `fleamarket`.`treasure_star`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`treasure_star` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`treasure_star` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `treasure_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_treasure_star_user1_idx` (`user_id` ASC),
  INDEX `fk_treasure_star_treasure1_idx` (`treasure_id` ASC),
  CONSTRAINT `fk_treasure_star_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_treasure_star_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品收藏';


-- -----------------------------------------------------
-- Table `fleamarket`.`treasure_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`treasure_picture` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`treasure_picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treasure_id` INT NOT NULL,
  `picture` VARCHAR(50) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_treasure_picture_treasure1_idx` (`treasure_id` ASC),
  CONSTRAINT `fk_treasure_picture_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`order` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`order` (
  `id` INT NOT NULL,
  `treasure_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` VARCHAR(50) NULL,
  `status` INT NOT NULL COMMENT '【订单状态】0：退货、1：待发货、2：已发货、3：交易成功',
  `logistics` VARCHAR(50) NULL COMMENT '物流单号，用于物流SDK',
  PRIMARY KEY (`id`),
  INDEX `fk_order_treasure1_idx` (`treasure_id` ASC),
  CONSTRAINT `fk_order_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`delivery_addr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`delivery_addr` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`delivery_addr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `consignee` VARCHAR(50) NOT NULL COMMENT '收件人',
  `tel` VARCHAR(11) NOT NULL,
  `isDefault` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivery_addr_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_delivery_addr_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`comment` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treasure_id` INT NOT NULL,
  `source_user_id` INT NOT NULL,
  `target_user_id` INT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_treasure1_idx` (`treasure_id` ASC),
  INDEX `fk_comment_user1_idx` (`source_user_id` ASC),
  CONSTRAINT `fk_comment_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`like` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_user_id` INT NOT NULL,
  `treasure_id` INT NOT NULL,
  `target_user_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_like_user1_idx` (`source_user_id` ASC),
  INDEX `fk_like_treasure1_idx` (`treasure_id` ASC),
  INDEX `fk_like_user2_idx` (`target_user_id` ASC),
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_user2`
    FOREIGN KEY (`target_user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`letter` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`letter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_user_id` INT NOT NULL,
  `target_user_id` INT NOT NULL,
  `content` VARCHAR(480) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_letter_user1_idx` (`source_user_id` ASC),
  INDEX `fk_letter_user2_idx` (`target_user_id` ASC),
  CONSTRAINT `fk_letter_user1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_letter_user2`
    FOREIGN KEY (`target_user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fleamarket`.`access_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleamarket`.`access_log` ;

CREATE TABLE IF NOT EXISTS `fleamarket`.`access_log` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `treasure_id` INT NOT NULL,
  `access_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_access_log_user1_idx` (`user_id` ASC),
  INDEX `fk_access_log_treasure1_idx` (`treasure_id` ASC),
  CONSTRAINT `fk_access_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fleamarket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_log_treasure1`
    FOREIGN KEY (`treasure_id`)
    REFERENCES `fleamarket`.`treasure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `fleamarket`;

DELIMITER $$

USE `fleamarket`$$
DROP TRIGGER IF EXISTS `fleamarket`.`treasure_star_AFTER_INSERT` $$
USE `fleamarket`$$
CREATE DEFINER = CURRENT_USER TRIGGER `fleamarket`.`treasure_star_AFTER_INSERT` AFTER INSERT ON `treasure_star` FOR EACH ROW
BEGIN
	UPDATE user SET star_count=star_count+1 WHERE id=new.user_id; 
END$$


USE `fleamarket`$$
DROP TRIGGER IF EXISTS `fleamarket`.`comment_AFTER_INSERT` $$
USE `fleamarket`$$
CREATE DEFINER = CURRENT_USER TRIGGER `fleamarket`.`comment_AFTER_INSERT` AFTER INSERT ON `comment` FOR EACH ROW
BEGIN
	UPDATE treasure SET comment_count=comment_count+1 WHERE id=NEW.treasure_id;
END$$


USE `fleamarket`$$
DROP TRIGGER IF EXISTS `fleamarket`.`like_AFTER_INSERT` $$
USE `fleamarket`$$
CREATE DEFINER = CURRENT_USER TRIGGER `fleamarket`.`like_AFTER_INSERT` AFTER INSERT ON `like` FOR EACH ROW
BEGIN
	UPDATE user SET like_count=like_count+1 WHERE id=NEW.target_user_id;
    UPDATE treasure SET like_count=like_count+1 WHERE id=NEW.treasure_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

