server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.118.28:3306/fleamarket?useSSL=false
    username: root
    password: Gaoshuai991.

mapper:
  not-empty: true
  identity: MYSQL


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fleamarket.core.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true
