server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.118.28:3306/fleamarket?useSSL=false
    username: root
    password: Gaoshuai991.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 40MB

mapper:
  not-empty: true
  identity: MYSQL

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
   width: 150
   height: 150
  tracker-list: 58.87.118.28:22122 # your profile

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fleamarket.core.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql